sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eDn0T/jF13rfY4oMfaxnI5FS5kNawnTYL0PRemfgWF3rogZSesxmSG15E7ReQpVJVD+b0vzE2uuOC0GovyDJCDBk24cX+mNOKpjccBGoM/RpZeEaXZd9/4Wg/2b/0ibRh5Rxhlt3K7h4Y6fUEmbJwj9xcZqoSZ3VMXqdIm2yyytGGTBjZ5V5ke5lD0MioFefHbItaR45hpWsZk/L0CmMHMDqvevoUfwV0K5Tk1cKCqDj0AUHO3ofIpvdQ/q5l668TWN9cRZeFCYn0dDSOtBay89AiAGBm9ko4yVbxoTkpns6nLVAfaKg5spVOupfBmkFBys1rdi+k85BmWZ4I4Whp+9TxR8X+EjEBrmT4O4hwl128zLKNp9XnrjRLqxb+hGCL7sqFq0lzZlpbOo2HF2JNZafs9PtB0TO7jvs3YDiaCdRNsIYuE+HQ4T4gUThOnjU7qFXLM84rILNE09gUwTuzHksZKM/czp+N3YJP1PZmXoGVIuz25RygV0U9E1TTcLlC2YwDlVeErUPQIws15lClKY4wgebWDwa3OeVRmklo9mN8O4lpeIQWiMDs6lL7cqIkwSXefLMeLchC1+sl4Vj36yLMts+HcfeA35P5BGG5wwpY0uBUCnUKuaU7kZBA8hJxWX2Od/hMlKL/rNeLThKokbOrKz5Y60+EhUdeZ2v5DU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Sipurim--Stories-_4778
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy